# Workshop configuration
title: "Modern PDFs processing with Natural PDF"
description: "Learn to extract data from PDFs with the ultimate spatial magic of Natural PDF"
github_repo: "jsoma/natural-pdf-workshop"
github_branch: "main"

# Workshop metadata
author: "Jonathan Soma"
date: "2025"

# Sections to process
sections:
  - title: "Natural PDF"
    folder: "."
    slides: "slides.pdf"

newsletter_signup: |
  <script async src="https://subscribe-forms.beehiiv.com/embed.js"></script><iframe src="https://subscribe-forms.beehiiv.com/0cfef682-b6ec-44eb-be72-e3241030da26" class="beehiiv-embed" data-test-id="beehiiv-embed" frameborder="0" scrolling="no" style="width: ; height: ; margin: 0; border-radius: 0px 0px 0px 0px !important; background-color: transparent; box-shadow: 0 0 #0000; max-width: 100%;"></iframe>

# Publishing options
output_dir: "docs"
index_template: |
  # {{ title }}
  
  **Jonathan Soma**, Columbia University

  **Contact:** [js4571@columbia.edu](mailto:js4571@columbia.edu) • [@dangerscarf](https://x.com/dangerscarf)
  
  **Sites:** [Lede Program](https://ledeprogram.com/) • [jonathansoma.com](https://jonathansoma.com/) • [Practical AI for Investigative Journalism](https://www.youtube.com/playlist?list=PLewNEVDy7gq1_GPUaL0OQ31QsiHP5ncAQ) • [Bad PDFs](https://badpdfs.com/)

  {{ description }}
    
  {{ notebooks }}

  {{ newsletter }}  

  ---
  
  *Created by {{ author }}*